## Data loading

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [4]:
pd.read_csv("../Data Analysis/raw/NorthBridgeDataset.xlsx - Agents.csv")
pd.read_csv("../Data Analysis/raw/NorthBridgeDataset.xlsx - Tickets.csv")
pd.read_csv("../Data Analysis/raw/NorthBridgeDataset.xlsx - Clients.csv")

,ClientID,ClientName,ClientType,ContractTier,AccountManagerID,Region,ContractStartDate,ContractEndDate,SLACreditClause,IsActive
0,1,Ashworth Medical Centre,Private Hospital,Premium,41,South East,2010-05-01,2013-10-19,0,1
1,2,Unity Health Clinic,Dental Group,Enterprise,92,Midlands,2016-03-01,2018-04-16,0,1
2,3,Junction Health Clinic,Private Hospital,Premium,76,Midlands,2014-08-01,2017-03-27,1,1
3,4,Arcadia Health Group,Mental Health Clinic,Enterprise,59,Yorkshire,2023-11-01,2028-08-12,1,1
4,5,Parkside Specialist Clinic,Private Hospital,Standard,102,Scotland,2014-09-01,2016-05-11,0,1
...,...,...,...,...,...,...,...,...,...,...
75,76,Crown Health Clinic,Physiotherapy Centre,Standard,88,Midlands,2015-11-01,2017-10-24,0,1
76,77,Central GP Practice,Mental Health Clinic,Enterprise,105,Scotland,2022-03-01,2023-07-08,1,0
77,78,County Health Clinic,Private Hospital,Standard,45,Yorkshire,2015-05-01,2019-03-21,0,1
78,79,Central GP Practice,GP Practice,Premium,41,North West,2013-05-01,2016-05-01,1,1
79,80,District Health Clinic,Physiotherapy Centre,Standard,86,Midlands,2016-12-01,2020-05-19,0,1

In [5]:
df_agents = pd.read_csv("../Data Analysis/raw/NorthBridgeDataset.xlsx - Agents.csv")
df_tickets = pd.read_csv("../Data Analysis/raw/NorthBridgeDataset.xlsx - Tickets.csv")
df_clients = pd.read_csv("../Data Analysis/raw/NorthBridgeDataset.xlsx - Clients.csv")

In [6]:
df_agents.head(10)
df_agents.info(10)
df_agents.describe()
df_agents.isnull().sum()
df_agents.duplicated().sum()
df_agents.columns.tolist

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AgentID        120 non-null    int64
 1   FullName       120 non-null    str
 2   TeamID         120 non-null    int64
 3   Role           120 non-null    str
 4   Specialisms    120 non-null    str
 5   Hub            120 non-null    str
 6   DailyCapacity  120 non-null    int64
 7   IsActive       120 non-null    int64
dtypes: int64(4), str(4)
memory usage: 7.6 KB

<bound method IndexOpsMixin.tolist of Index(['AgentID', 'FullName', 'TeamID', 'Role', 'Specialisms', 'Hub',
       'DailyCapacity', 'IsActive'],
      dtype='str')>

In [7]:
df_tickets.head(10)
df_tickets.info(10)
df_tickets.describe()
df_tickets.isnull().sum()
df_tickets.duplicated().sum()
df_tickets.columns.tolist

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TicketID         3500 non-null   int64
 1   TicketReference  3500 non-null   str
 2   ClientID         3500 non-null   int64
 3   PatientRef       3500 non-null   str
 4   CategoryID       3500 non-null   int64
 5   PriorityID       3500 non-null   int64
 6   Status           3500 non-null   str
 7   AssignedAgentID  3500 non-null   int64
 8   CreatedAt        3500 non-null   str
 9   FirstResponseAt  3454 non-null   str
 10  ResolvedAt       3301 non-null   str
 11  SLADueAt         3500 non-null   str
 12  SLABreached      3500 non-null   int64
 13  Channel          3500 non-null   str
 14  Description      3500 non-null   str
 15  ResolutionNotes  3301 non-null   str
dtypes: int64(6), str(10)
memory usage: 437.6 KB

<bound method IndexOpsMixin.tolist of Index(['TicketID', 'TicketReference', 'ClientID', 'PatientRef', 'CategoryID',
       'PriorityID', 'Status', 'AssignedAgentID', 'CreatedAt',
       'FirstResponseAt', 'ResolvedAt', 'SLADueAt', 'SLABreached', 'Channel',
       'Description', 'ResolutionNotes'],
      dtype='str')>

In [8]:
df_clients.head(10)
df_clients.info(10)
df_clients.describe()
df_clients.isnull().sum()
df_clients.duplicated().sum()
df_clients.columns.tolist()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ClientID           80 non-null     int64
 1   ClientName         80 non-null     str
 2   ClientType         80 non-null     str
 3   ContractTier       80 non-null     str
 4   AccountManagerID   80 non-null     int64
 5   Region             80 non-null     str
 6   ContractStartDate  80 non-null     str
 7   ContractEndDate    80 non-null     str
 8   SLACreditClause    80 non-null     int64
 9   IsActive           80 non-null     int64
dtypes: int64(4), str(6)
memory usage: 6.4 KB

['ClientID',
 'ClientName',
 'ClientType',
 'ContractTier',
 'AccountManagerID',
 'Region',
 'ContractStartDate',
 'ContractEndDate',
 'SLACreditClause',
 'IsActive']

## Joining the client and ticket table

In [9]:
tickets_clients = df_tickets.merge(df_clients, on="ClientID", how="left")

In [10]:
final_df = tickets_clients.merge( df_agents,left_on="AssignedAgentID",right_on="AgentID",how="left",
    suffixes=("", "_Agent"))

final_df.head()

,TicketID,TicketReference,ClientID,PatientRef,CategoryID,PriorityID,Status,AssignedAgentID,CreatedAt,FirstResponseAt,...,SLACreditClause,IsActive,AgentID,FullName,TeamID,Role,Specialisms,Hub,DailyCapacity,IsActive_Agent
0,1,NB-2024-00001,70,PT-81496,5,3,Closed,111,2024-07-24 23:41,2024-07-25 02:27,...,0,1,111,Rhona Murphy,8,Senior Agent,"Complaint,Appointment Change,Document Request",Edinburgh,16,1
1,2,NB-2024-00002,51,PT-99051,2,1,Closed,32,2024-11-06 23:45,2024-11-07 01:09,...,0,1,32,Charlie Nowak,1,Team Lead,"Document Request,Appointment Change,Insurance ...",Manchester,8,1
2,3,NB-2024-00003,53,PT-24869,3,3,Closed,57,2024-08-01 05:39,2024-08-01 09:58,...,0,1,57,Sophia Doyle,4,Agent,"Complaint,Billing Issue,Insurance Query",Leeds,21,1
3,4,NB-2024-00004,11,PT-55537,1,2,Closed,22,2024-12-03 13:22,2024-12-03 14:47,...,1,1,22,Freddie Wilson,1,Agent,"Billing Issue,Document Request,Appointment Change",Manchester,27,1
4,5,NB-2023-00005,70,PT-50539,3,2,Resolved,52,2023-02-11 03:56,2023-02-11 06:27,...,0,1,52,Alfie Stewart,4,Agent,"Billing Issue,Insurance Query,Document Request",Leeds,26,1

In [11]:
print(final_df.shape)
print(final_df.head())
print(final_df.columns.tolist())

(3500, 33)
   TicketID TicketReference  ClientID PatientRef  CategoryID  PriorityID  \
0         1   NB-2024-00001        70   PT-81496           5           3
1         2   NB-2024-00002        51   PT-99051           2           1
2         3   NB-2024-00003        53   PT-24869           3           3
3         4   NB-2024-00004        11   PT-55537           1           2
4         5   NB-2023-00005        70   PT-50539           3           2

     Status  AssignedAgentID         CreatedAt   FirstResponseAt  ...  \
0    Closed              111  2024-07-24 23:41  2024-07-25 02:27  ...
1    Closed               32  2024-11-06 23:45  2024-11-07 01:09  ...
2    Closed               57  2024-08-01 05:39  2024-08-01 09:58  ...
3    Closed               22  2024-12-03 13:22  2024-12-03 14:47  ...
4  Resolved               52  2023-02-11 03:56  2023-02-11 06:27  ...

  SLACreditClause IsActive  AgentID        FullName TeamID          Role  \
0               0        1      111    Rhona Murphy      8  Senior Agent
1               0        1       32   Charlie Nowak      1     Team Lead
2               0        1       57    Sophia Doyle      4         Agent
3               1        1       22  Freddie Wilson      1         Agent
4               0        1       52   Alfie Stewart      4         Agent

                                         Specialisms         Hub  \
0      Complaint,Appointment Change,Document Request   Edinburgh
1  Document Request,Appointment Change,Insurance ...  Manchester
2            Complaint,Billing Issue,Insurance Query       Leeds
3  Billing Issue,Document Request,Appointment Change  Manchester
4     Billing Issue,Insurance Query,Document Request       Leeds

  DailyCapacity  IsActive_Agent
0            16               1
1             8               1
2            21               1
3            27               1
4            26               1

[5 rows x 33 columns]
['TicketID', 'TicketReference', 'ClientID', 'PatientRef', 'CategoryID', 'PriorityID', 'Status', 'AssignedAgentID', 'CreatedAt', 'FirstResponseAt', 'ResolvedAt', 'SLADueAt', 'SLABreached', 'Channel', 'Description', 'ResolutionNotes', 'ClientName', 'ClientType', 'ContractTier', 'AccountManagerID', 'Region', 'ContractStartDate', 'ContractEndDate', 'SLACreditClause', 'IsActive', 'AgentID', 'FullName', 'TeamID', 'Role', 'Specialisms', 'Hub', 'DailyCapacity', 'IsActive_Agent']

In [12]:
print(final_df["ClientName"].isna().sum())

0

In [13]:
print("Tickets + Clients:", len(tickets_clients))
print("Final dataset:", len(final_df))
print("Missing AgentID after merge:", final_df["AgentID"].isna().sum())

Tickets + Clients: 3500
Final dataset: 3500
Missing AgentID after merge: 0

### INSPECTING THE JOINED DATASET

In [14]:
final_df.head()
final_df.info()
final_df.describe()
final_df.columns.tolist()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TicketID           3500 non-null   int64
 1   TicketReference    3500 non-null   str
 2   ClientID           3500 non-null   int64
 3   PatientRef         3500 non-null   str
 4   CategoryID         3500 non-null   int64
 5   PriorityID         3500 non-null   int64
 6   Status             3500 non-null   str
 7   AssignedAgentID    3500 non-null   int64
 8   CreatedAt          3500 non-null   str
 9   FirstResponseAt    3454 non-null   str
 10  ResolvedAt         3301 non-null   str
 11  SLADueAt           3500 non-null   str
 12  SLABreached        3500 non-null   int64
 13  Channel            3500 non-null   str
 14  Description        3500 non-null   str
 15  ResolutionNotes    3301 non-null   str
 16  ClientName         3500 non-null   str
 17  ClientType         3500 non-null   str
 18  ContractTier       3500 non-null   str
 19  AccountManagerID   3500 non-null   int64
 20  Region             3500 non-null   str
 21  ContractStartDate  3500 non-null   str
 22  ContractEndDate    3500 non-null   str
 23  SLACreditClause    3500 non-null   int64
 24  IsActive           3500 non-null   int64
 25  AgentID            3500 non-null   int64
 26  FullName           3500 non-null   str
 27  TeamID             3500 non-null   int64
 28  Role               3500 non-null   str
 29  Specialisms        3500 non-null   str
 30  Hub                3500 non-null   str
 31  DailyCapacity      3500 non-null   int64
 32  IsActive_Agent     3500 non-null   int64
dtypes: int64(13), str(20)
memory usage: 902.5 KB

['TicketID',
 'TicketReference',
 'ClientID',
 'PatientRef',
 'CategoryID',
 'PriorityID',
 'Status',
 'AssignedAgentID',
 'CreatedAt',
 'FirstResponseAt',
 'ResolvedAt',
 'SLADueAt',
 'SLABreached',
 'Channel',
 'Description',
 'ResolutionNotes',
 'ClientName',
 'ClientType',
 'ContractTier',
 'AccountManagerID',
 'Region',
 'ContractStartDate',
 'ContractEndDate',
 'SLACreditClause',
 'IsActive',
 'AgentID',
 'FullName',
 'TeamID',
 'Role',
 'Specialisms',
 'Hub',
 'DailyCapacity',
 'IsActive_Agent']

In [15]:
print("Duplicate rows:", final_df.duplicated().sum())
print("Duplicate TicketIDs:", final_df["TicketID"].duplicated().sum())
print(final_df["PriorityID"].value_counts().sort_index())

Duplicate rows: 0
Duplicate TicketIDs: 0
PriorityID
1     258
2     833
3    1981
4     428
Name: count, dtype: int64

In [16]:
print(final_df["Status"].value_counts())
print(final_df["PriorityID"].value_counts())
print(final_df["Channel"].value_counts())
print(final_df["ContractTier"].value_counts())

Status
Closed            1984
Resolved          1317
Escalated           57
In Progress         52
Open                46
Pending Client      44
Name: count, dtype: int64
PriorityID
3    1981
2     833
4     428
1     258
Name: count, dtype: int64
Channel
Email     1221
Portal     977
Phone      905
Form       397
Name: count, dtype: int64
ContractTier
Standard      1662
Premium       1295
Enterprise     543
Name: count, dtype: int64

In [17]:
date_columns = ["CreatedAt","FirstResponseAt","ResolvedAt","SLADueAt","ContractStartDate","ContractEndDate"]

print(final_df[date_columns].dtypes)

CreatedAt            str
FirstResponseAt      str
ResolvedAt           str
SLADueAt             str
ContractStartDate    str
ContractEndDate      str
dtype: object

In [18]:
missing_values = final_df.isnull().sum()

print(missing_values[missing_values > 0])

FirstResponseAt     46
ResolvedAt         199
ResolutionNotes    199
dtype: int64

In [21]:

final_df[final_df["ResolvedAt"].isna()]["Status"].value_counts()
final_df[final_df["FirstResponseAt"].isna()]["Status"].value_counts()
final_df[final_df["ResolutionNotes"].isna()]["Status"].value_counts()

print(final_df[final_df["ResolvedAt"].isna()]["Status"].value_counts())
print(final_df[final_df["FirstResponseAt"].isna()]["Status"].value_counts())

Status
Escalated         57
In Progress       52
Open              46
Pending Client    44
Name: count, dtype: int64
Status
Open    46
Name: count, dtype: int64

In [22]:
final_df.groupby("Status")["ResolvedAt"].apply(lambda x: x.isna().sum())
pd.crosstab( final_df["Status"], final_df["ResolutionNotes"].isna())

ResolutionNotes  False  True
Status
Closed            1984      0
Escalated            0     57
In Progress          0     52
Open                 0     46
Pending Client       0     44
Resolved          1317      0

In [23]:
print("Missing ResolvedAt:")
print(final_df[final_df["ResolvedAt"].isna()]["Status"].value_counts())

print("\nMissing FirstResponseAt:")
print(final_df[final_df["FirstResponseAt"].isna()]["Status"].value_counts())

print("\nMissing ResolutionNotes:")
print(final_df[final_df["ResolutionNotes"].isna()]["Status"].value_counts())

Missing ResolvedAt:
Status
Escalated         57
In Progress       52
Open              46
Pending Client    44
Name: count, dtype: int64

Missing FirstResponseAt:
Status
Open    46
Name: count, dtype: int64

Missing ResolutionNotes:
Status
Escalated         57
In Progress       52
Open              46
Pending Client    44
Name: count, dtype: int64

In [27]:
final_df["IsResolved"] = final_df["ResolvedAt"].notna().astype(int)
final_df["IsResolved"] = (final_df["ResolvedAt"].notna().astype(int))
final_df["ResolutionNotesAvailable"] = (final_df["ResolutionNotes"].notna().astype(int))

In [ ]:
final_df["FirstResponseAvailable"] = final_df["FirstResponseAt"].notna().astype(int)
print(final_df["FirstResponseAvailable"].value_counts())
print(final_df["IsResolved"].value_counts())
print(final_df["ResolutionNotesAvailable"].value_counts())

KeyError: 'FirstResponseAvailable'